global using EFSoft.Orders.Application.Commands.Parameters;
global using EFSoft.Orders.Application.Queries.Parameters;
global using EFSoft.Orders.Application.Queries.Results;
global using EFSoft.Orders.Application.RepositoryContracts;
global using EFSoft.Orders.Domain.Enums;
global using EFSoft.Orders.Domain.Models;
global using EFSoft.Shared.Cqrs.Command;
global using EFSoft.Shared.Cqrs.Handler;
global using EFSoft.Shared.Cqrs.Query;
